#! /bin/bash


if [ $EUID -ne 0 ]; then
    echo "You are not the admin I am looking for."
else
    echo "Hello, this is running with root/sudo."

function installs () {

sudo apt-get install htop python3 python3-pip ack

 }

installs 
echo "Programs have been installed!"

function motd-message () {

sudo run-parts /etc/update-motd.d/

}

motd-message
echo "Thanks for displaying my custom message!"

 
fi







